development:
  access_key: 'AKIAJDSU5CTXKVEMH6OA'
  secret_access_key: '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'
  endpoint: 'https://fps.sandbox.amazonaws.com/'
  pipeline: 'https://authorize.payments-sandbox.amazon.com/cobranded-ui/actions/start?'
  version: '2007-01-08'

test:
  access_key: 'AKIAJDSU5CTXKVEMH6OA'
  secret_access_key: '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'
  endpoint: 'https://fps.sandbox.amazonaws.com/'
  pipeline: 'https://authorize.payments-sandbox.amazon.com/cobranded-ui/actions/start?'
  version: '2007-01-08'

production:
  access_key: 'AKIAJDSU5CTXKVEMH6OA'
  secret_access_key: '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'
  endpoint: 'https://fps.amazonaws.com/'
  pipeline: 'https://authorize.payments.amazon.com/cobranded-ui/actions/start?'
  version: '2007-01-08'
